services:
  postgres:
    image: postgres:16-alpine
    container_name: python-all-postgres
    environment:
      POSTGRES_DB: learn_db
      POSTGRES_USER: learn_user
      POSTGRES_PASSWORD: learn_pass
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U learn_user -d learn_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
