#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MODULE_DIR="$(dirname "$SCRIPT_DIR")"
ROOT_DIR="$(dirname "$MODULE_DIR")"

echo "=============================================="
echo " CAPSTONE DEMO — Module 15 + 23 + 24"
echo "=============================================="
echo ""
echo "Terminal 1 — Agent Bridge (Module 23):"
echo "  bash $ROOT_DIR/23-mcp-ai-agent-awx/scripts/04-run-agent-bridge.sh"
echo ""
echo "Terminal 2 — n8n (Module 24):"
echo "  bash $MODULE_DIR/scripts/02-deploy-n8n-compose.sh"
echo ""
echo "Terminal 3 — AWX port-forward (Module 15, nếu AWX thật):"
echo "  kubectl port-forward svc/awx-service 8052:80 -n awx"
echo ""
echo "n8n UI → Import workflows/04-capstone-ai-ops.json → Activate"
echo "Test:"
echo "  bash $MODULE_DIR/scripts/04-test-webhook.sh"
echo ""
echo "Hoặc test bridge trực tiếp:"
echo "  python $ROOT_DIR/23-mcp-ai-agent-awx/examples/02_call_bridge_api.py --intent list_templates"
